export const ROLES = {
  SUPER_ADMIN: "super_admin",
  STORE_MANAGER: "store_manager",
  SALES_ASSOCIATE_AND_INVENTORY_MANAGER: "sales_associate_and_inventory_manager",
  SALES_ASSOCIATE: "sales_associate",
  INVENTORY_MANAGER: "inventory_manager",
  HR: "hr",
  IT_SUPPORT: "it_support",
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: "view_dashboard",
  MANAGE_USERS: "manage_users",
  VIEW_REPORTS: "view_reports",
  MANAGE_INVENTORY: "manage_inventory",
  MANAGE_PAYROLL: "manage_payroll",
  MANAGE_SETTINGS: "manage_settings",
  PROCESS_SALES: "process_sales",
};

export const BASE_PERMISSIONS = {
  MANAGE_STORE: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.PROCESS_SALES,
  ],
  MANAGE_SYSTEM: [PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_SETTINGS],
  MANAGE_HR: [PERMISSIONS.MANAGE_PAYROLL],
};

export const rolePermissions = {
  [ROLES.SUPER_ADMIN]: [
    ...BASE_PERMISSIONS.MANAGE_STORE,
    ...BASE_PERMISSIONS.MANAGE_SYSTEM,
    ...BASE_PERMISSIONS.MANAGE_HR,
  ],
  [ROLES.STORE_MANAGER]: [
    ...BASE_PERMISSIONS.MANAGE_STORE,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  [ROLES.SALES_ASSOCIATE]: [PERMISSIONS.PROCESS_SALES],
  [ROLES.SALES_ASSOCIATE_AND_INVENTORY_MANAGER]: [PERMISSIONS.PROCESS_SALES,PERMISSIONS.MANAGE_INVENTORY],
  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  [ROLES.HR]: [...BASE_PERMISSIONS.MANAGE_HR],
  [ROLES.IT_SUPPORT]: [PERMISSIONS.MANAGE_SETTINGS],
};

export const getPermissionsForRole = (role) => rolePermissions[role] || [];
